[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["src/lib/**"]
  external_node_modules = ["@octokit/rest"]

[build.environment]
  NODE_VERSION = "18"
  
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  
[functions.scan-repository]
  timeout = 30 # Increase timeout to 30 seconds
  memory = 1024 # Increase memory to 1GB
