[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@octokit/rest"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*.jsx"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline'; object-src 'none';"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"