[build]
command = "npm run build && npm run build:functions"
functions = "netlify/functions"
publish = "dist"



[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["src/lib/**"]
  external_node_modules = ["@octokit/rest"]

[functions.scan-repository]
  timeout = 30
  memory = 1024
  node_bundler = "esbuild"

[functions.scan-webpage]
  timeout = 30
  memory = 1024
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
