[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["src/lib/**"]
  external_node_modules = ["@octokit/rest"]
  
[functions.scan-repository]
  timeout = 30 # Increase timeout to 30 seconds
  memory = 1024 # Increase memory to 1GB